// generated by chatGTP :)

const rotate = (arr) => {
  const result = new Array(arr[0].length).fill(0).map(() => new Array(arr.length).fill(0))

  for (let i = 0; i < arr.length; i++) {
    for (let j = 0; j < arr[0].length; j++) {
      result[j][arr.length - i - 1] = arr[i][j]
    }
  }

  return result
}

const union = (arr1, arr2) => {
  const or = (arr1, arr2) => {
    const result = []
    for (let i = 0; i < arr1.length; i++) {
      result.push(arr1[i] | arr2[i])
    }
    return result
  }

  return arr1.map((r1, i) => {
    const r2 = arr2[i]
    return or(r1, r2)
  })
}

function fill(i, j, fill) {
  const result = []
  for (let x = 0; x < i; x++) {
    let row = []
    for (let y = 0; y < j; y++) {
      row.push(fill)
    }
    result.push(row)
  }
  return result
}

function sum(arr) {
  let result = 0

  for (let i = 0; i < arr.length; i++) {
    for (let j = 0; j < arr[i].length; j++) {
      result += arr[i][j]
    }
  }

  return result
}

export {
  rotate,
  union,
  fill,
  sum
}
